name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
        export BOOTSTRAP_HASKELL_NONINTERACTIVE=1
        export BOOTSTRAP_HASKELL_GHC_VERSION=9.8.2
        export BOOTSTRAP_HASKELL_CABAL_VERSION=3.12.1.0
        export BOOTSTRAP_HASKELL_INSTALL_HLS=0
        export BOOTSTRAP_HASKELL_INSTALL_NO_STACK=1
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
    # - uses: actions/setup-haskell@v1
    #   with:
    #     ghc-version: '9.8.2'
    #     cabal-version: '3.12.1.0'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all
